#include <stdio.h>

/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
unsigned int fib(unsigned int n) 
{ 
  if (n == 0 || n == 1) return n;
  else return fib(n - 1) + fib(n - 2);
}


int main (int argc, char ** argv)
{
  unsigned int a = 0, total = 0;
  while (1) 
  {
    unsigned int res = fib(a++);
    if (res > 4000000) break; 
    total += (res % 2 == 0) ? res : 0;
  }
  printf("%d\n", total);
  return 0;
}
